FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Models/DriverOffence.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Data.Linq.Mapping;
//using System.ComponentModel.DataAnnotations;


namespace OOPenaltyPoints.Models
{    
    [Table(Name = "DriverOffences")]
    public class DriverOffence
    {           
        [Column(IsPrimaryKey = true, IsDbGenerated = true)] //Note
        public int Id { get; set; }
        [Column(DbType = "NOT NULL")]  //<--- issue
        public System.DateTime doOffenceDate { get; set; }

        //CC - Add location
        [Column(DbType = "NULL")]
        public string doLocation { get; set; }

        //CC - removed doRegistration and doLicenceNo as in DriverDetail and Vechile detail object
        //[Column(DbType = "NOT NULL")]  //<--- issue
        //public string doRegistration { get; set; }
         //[Column(DbType = "NOT NULL")]
        //public string doLicenceNo { get; set; }


        [Column(DbType = "NULL")]
        public string doStatus { get; set; }

        //CC - removed doPoitsApplied and doPointsDate as should be in Summons and Notificaton table
        //[Column(DbType = "NULL")]
       // public int doPointsApplied { get; set; }
        //[Column(DbType = " NULL")]
        //public System.DateTime doPointsDate { get; set; }
        
        [Column(DbType = " NULL")]
        public string doGardaId { get; set; }

        //CC-removed virtual from all listedoffence, vechicledetails, driverdetails
        //m:1
        [Column] public virtual ListedOffence ListedOffence { get; set; }

        //m:1
        [Column] public virtual VehicleDetail VehicleDetails { get; set; }

        //m:1
        [Column] public virtual DriverDetail DriverDetail { get; set; }
        
        public DriverOffence()
        {
        }

        //CC - Updated Constructor
        public DriverOffence(System.DateTime _doOffenceDate, string _doStatus, string _doLocation, string _doGardaId,
        string _DdLicenceNo, string _DdFName, string _DdSName, string _DdAddress1, 
        string _DdAddress2, string _DdAddress3, string _DdLicenceStatus,
        string _VdRegistration, string _VdType, string _VdMake, decimal _VdCubicCapacity)
        {
            //DriverOffence
            this.doOffenceDate = _doOffenceDate;
            this.doStatus = _doStatus;
            this.doLocation = _doLocation;
            this.doGardaId = _doGardaId;

            //DriverDetails
            this.DriverDetail.DdLicenceNo = _DdLicenceNo;
            this.DriverDetail.DdFName = _DdFName;
            this.DriverDetail.DdSName = _DdSName;
            this.DriverDetail.DdAddress1 = _DdAddress1;
            this.DriverDetail.DdAddress2 = _DdAddress2;
            this.DriverDetail.DdAddress3 = _DdAddress3;
            this.DriverDetail.DdLicenceStatus = _DdLicenceStatus;

            //VehicleDetails
            this.VehicleDetails.VdRegistration = _VdRegistration;
            this.VehicleDetails.VdType = _VdType;
            this.VehicleDetails.VdMake = _VdMake;
            this.VehicleDetails.VdCubicCapacity = _VdCubicCapacity;
        }
    }
}

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Controllers/DriverOffenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Linq.Mapping;
using System.Web;
using System.Web.Mvc;
using OOPenaltyPoints.BLL;
using OOPenaltyPoints.Models.ViewModel;
using OOPenaltyPoints.Models;

namespace OOPenaltyPoints.Controllers
{
    public class DriverOffenceController : Controller
    {
        private DriverOffenceBLL _driverOffenceBLL = null;

        protected DriverOffenceBLL _BLL
        {
            get
            {
                if (_driverOffenceBLL == null)
                    _driverOffenceBLL = new DriverOffenceBLL();

                return _driverOffenceBLL;
            }
        }
        /// <method>
        /// GET: /DriverOffence/Index
        /// Index() returns all active offences to UI.
        /// </method>
        [Authorize(Roles = "Super, Worker")]
        public ActionResult Index()
        {
            return View(_BLL.GetOffences());
        }

        /// <method>
        /// Create() displays UI to create a new driver offence.
        /// GET: /DriverOffence/Create
        /// </method>
        [Authorize(Roles = "Super, Worker")]
        public ActionResult Create()
        {
            List<SelectListItem> doStatus = new List<SelectListItem>();
            List<SelectListItem> licenceStatus = new List<SelectListItem>();
            List<SelectListItem> County = new List<SelectListItem>();
            List<SelectListItem> doDescription = new List<SelectListItem>();

            //Define a driver offence status list
            doStatus.Add(new SelectListItem
            {
                Text = "New Offence",
                Value = "New Offence",
                Selected = true
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Penalty Notification",
                Value = "Penalty Notification"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "28 Days Notification",
                Value = "28 Days Notification"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Court Summons",
                Value = "Court Summons"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Fine Paid",
                Value = "Fine Paid"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Deleted",
                Value = "Deleted"
            });
           
            //Define a driver licence status list
            licenceStatus.Add(new SelectListItem
            {
                Text = "Full Licence",
                Value = "Full Licence",
                Selected = true
            });
            licenceStatus.Add(new SelectListItem
            {
                Text = "Provisional Licence",
                Value = "Provisional Licence"
            });
            licenceStatus.Add(new SelectListItem
            {
                Text = "Disqualified",
                Value = "Disqualified"
            });
            licenceStatus.Add(new SelectListItem
            {
                Text = "No Valid Licence",
                Value = "No Valid Licence"
            });
            licenceStatus.Add(new SelectListItem
            {
                Text = "Other",
                Value = "Other"
            });

            //Define a county name list
            County.Add(new SelectListItem
            {
                Text = "Carlow",
                Value = "Carlow"
            });
            County.Add(new SelectListItem
            {
                Text = "Cavan",
                Value = "Cavan"
            });
            County.Add(new SelectListItem
            {
                Text = "Clare",
                Value = "Clare"
            });
            County.Add(new SelectListItem
            {
                Text = "Cork",
                Value = "Cork"
            });
            County.Add(new SelectListItem
            {
                Text = "Donegal",
                Value = "Donegal"
            });
            County.Add(new SelectListItem
            {
                Text = "Dublin",
                Value = "Dublin"
            });
            County.Add(new SelectListItem
            {
                Text = "Galway",
                Value = "Galway",
                Selected = true
            });
            County.Add(new SelectListItem
            {
                Text = "Kerry",
                Value = "Kerry"
            });
            County.Add(new SelectListItem
            {
                Text = "Kildare",
                Value = "Kildare"
            });
            County.Add(new SelectListItem
            {
                Text = "Kilkenny",
                Value = "Kilkenny"
            });
            County.Add(new SelectListItem
            {
                Text = "Laois",
                Value = "Laois"
            });
            County.Add(new SelectListItem
            {
                Text = "Leitrim",
                Value = "Leitrim"
            });
            County.Add(new SelectListItem
            {
                Text = "Limerick",
                Value = "Limerick"
            });
            County.Add(new SelectListItem
            {
                Text = "Longford",
                Value = "Longford"
            });
            County.Add(new SelectListItem
            {
                Text = "Louth",
                Value = "Louth"
            });
            County.Add(new SelectListItem
            {
                Text = "Mayo",
                Value = "Mayo"
            });
            County.Add(new SelectListItem
            {
                Text = "Meath",
                Value = "Meath"
            });
            County.Add(new SelectListItem
            {
                Text = "Monaghan",
                Value = "Monaghan"
            });
            County.Add(new SelectListItem
            {
                Text = "Offaly",
                Value = "Offaly"
            });
            County.Add(new SelectListItem
            {
                Text = "Roscommon",
                Value = "Roscommon"
            });
            County.Add(new SelectListItem
            {
                Text = "Sligo",
                Value = "Sligo"
            });
            County.Add(new SelectListItem
            {
                Text = "Tipperary",
                Value = "Tipperary"
            });
            County.Add(new SelectListItem
            {
                Text = "Waterford",
                Value = "Waterford"
            });
            County.Add(new SelectListItem
            {
                Text = "Westmeath",
                Value = "Westmeath"
            });
            County.Add(new SelectListItem
            {
                Text = "Wexford",
                Value = "Wexford"
            });
            County.Add(new SelectListItem
            {
                Text = "Wicklow",
                Value = "Wicklow"
            });
            County.Add(new SelectListItem
            {
                Text = "Other",
                Value = "Other"
            });

            //Define a offence description list
            ListedOffenceBLL listedOffenceBLL = new ListedOffenceBLL();
            doDescription = listedOffenceBLL.GetOffenceDescription();

            ViewData["doDescription"] = new SelectList(doDescription, "Value", "Text");
            ViewData["doStatus"] = new SelectList(doStatus, "Value", "Text");
            ViewData["licenceStatus"] = new SelectList(licenceStatus, "Value", "Text");
            ViewData["County"] = new SelectList(County, "Value", "Text");
            return View();
        }

        /// <method>
        /// Create() inserts a new driver offence into the database.
        /// POST: /DriverOffence/Create
        /// </method>
        [HttpPost]
        public ActionResult Create(DriverOffenceUI OffenceUI)
        {
            //List<SelectListItem> doDescription = new List<SelectListItem>();
            //ListedOffenceBLL listedOffenceBLL = new ListedOffenceBLL();
            //doDescription = listedOffenceBLL.GetOffenceDescription();
            //ViewData["doDescription"] = new SelectList(doDescription, "Value", "Text");
            List<SelectListItem> doStatus = new List<SelectListItem>();
            List<SelectListItem> licenceStatus = new List<SelectListItem>();
            List<SelectListItem> County = new List<SelectListItem>();
            List<SelectListItem> doDescription = new List<SelectListItem>();

            //Define a driver offence status list
            doStatus.Add(new SelectListItem
            {
                Text = "New Offence",
                Value = "New Offence",
                Selected = true
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Penalty Notification",
                Value = "Penalty Notification"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "28 Days Notification",
                Value = "28 Days Notification"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Court Summons",
                Value = "Court Summons"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Fine Paid",
                Value = "Fine Paid"
            });
            doStatus.Add(new SelectListItem
            {
                Text = "Deleted",
                Value = "Deleted"
            });

            //Define a driver licence status list
            licenceStatus.Add(new SelectListItem
            {
                Text = "Full Licence",
                Value = "Full Licence",
                Selected = true
            });
            licenceStatus.Add(new SelectListItem
            {
                Text = "Provisional Licence",

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/AutoGenCreate.cshtml
@model OOPenaltyPoints.Models.DriverOffence

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>DriverOffence</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.doOffenceDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doOffenceDate)
            @Html.ValidationMessageFor(model => model.doOffenceDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.doRegistration)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doRegistration)
            @Html.ValidationMessageFor(model => model.doRegistration)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.doLicenceNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doLicenceNo)
            @Html.ValidationMessageFor(model => model.doLicenceNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.doStatus)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doStatus)
            @Html.ValidationMessageFor(model => model.doStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.doPointsApplied)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doPointsApplied)
            @Html.ValidationMessageFor(model => model.doPointsApplied)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.doPointsDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.doPointsDate)
            @Html.ValidationMessageFor(model => model.doPointsDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/Create.cshtml
@model OOPenaltyPoints.Models.ViewModel.DriverOffenceUI

@{
    ViewBag.Title = "Create";
}

<h2>Create A New Driving Offence</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
 
       <fieldset>
        <legend>Fill in the details of the penalty point offence and click 'Create' button when done.</legend>
           <br />

          <!--------Details of driving offence committed ----------->

           <fieldset>
            <legend>Driving Offence Information:</legend>
            <br />
            @Html.LabelFor(model => model.description,"Description:")
            @Html.DropDownListFor(model => model.description, (SelectList)ViewData["doDescription"])
            @Html.ValidationMessageFor(model => model.description,"Required.")

            @Html.LabelFor(model => model.gardaId, "Garda Identification No:")
            @Html.EditorFor(model => model.gardaId)
            @Html.ValidationMessageFor(model => model.gardaId, "Required.")

            <br /><br />

            @Html.LabelFor(model => model.location, "Location:")
            @Html.EditorFor(model => model.location)
            @Html.ValidationMessageFor(model => model.location, "Required.")

            @Html.LabelFor(model => model.offenceDate, "Date:")
            @Html.EditorFor(model => model.offenceDate)
            @Html.ValidationMessageFor(model => model.offenceDate, "Required.")

            <br /><br />

            @Html.LabelFor(model => model.status, "Status:")
            @Html.DropDownListFor(model => model.status, (SelectList)ViewData["doStatus"])
            @Html.ValidationMessageFor(model => model.status, "Required.")
            <br />
            </fieldset>
            
<!--------Details of driver who committed the offence ----------->

            <fieldset>
            <legend>Driver Information</legend>
            <br />
            @Html.LabelFor(model => model.LicenceNo, "Drivers licence number (or PPSN No):")
            @Html.EditorFor(model => model.LicenceNo)
            @Html.ValidationMessageFor(model => model.LicenceNo, "Required.")

            @Html.LabelFor(model => model.LicenceStatus, "Status:")
            @Html.DropDownListFor(model => model.LicenceStatus, (SelectList)ViewData["licenceStatus"])
            @Html.ValidationMessageFor(model => model.LicenceStatus, "Required.")

            <br /><br />

            @Html.LabelFor(model => model.FName,"First Name:")
            @Html.EditorFor(model => model.FName)
            @Html.ValidationMessageFor(model => model.FName, "Required.")

            @Html.LabelFor(model => model.SName,"Surname:")
            @Html.EditorFor(model => model.SName)
            @Html.ValidationMessageFor(model => model.SName, "Required.")

            <br /><br />

            @Html.LabelFor(model => model.Address1, "Address:")
            @Html.EditorFor(model => model.Address1)
            @Html.ValidationMessageFor(model => model.Address1, "Required.")

            @Html.LabelFor(model => model.Address2, "Town etc:")
            @Html.EditorFor(model => model.Address2)
            @Html.ValidationMessageFor(model => model.Address2, "Required.")

            @Html.LabelFor(model => model.Address3, "County:")
            @Html.DropDownListFor(model => model.Address3, (SelectList)ViewData["County"])
            @Html.ValidationMessageFor(model => model.Address3, "Required.")
            <br />
            </fieldset>
         
            <!--------Details of vehicle used in the committed offence ----------->
   
            <fieldset>
            <legend>Vehicle Information</legend>
            <br />
            @Html.LabelFor(model => model.Registration, "Registration No:")
            @Html.EditorFor(model => model.Registration)
            @Html.ValidationMessageFor(model => model.Registration, "Required.") 

            @Html.LabelFor(model => model.Make, "Make:")
            @Html.EditorFor(model => model.Make)
            @Html.ValidationMessageFor(model => model.Make, "Required.")

            <br /><br />
                 
            @Html.LabelFor(model => model.Type, "Type:")
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type, "Required.")

            @Html.LabelFor(model => model.Capacity, "Capacity:")
            @Html.EditorFor(model => model.Capacity)
            @Html.ValidationMessageFor(model => model.Capacity, "Required.")
            <br />

            </fieldset>

        </fieldset>
        <p>
            <input type="submit" value="Create" />
        </p>
 
    
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/DailyTasks.cshtml
@model OOPenaltyPoints.Models.ViewModel.DailyTasksUI

@{
    ViewBag.Title = "DailyTasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Driver Offences Daily Tasks</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
 
       <fieldset>
        <legend>Select the task you wish to run and click the 'Run Task' button when done.</legend>
           <br />

          <!--------Select From the Daily Task list ----------->

            @Html.LabelFor(model => model.Name, "Tasks: ")
            @Html.DropDownListFor(model => model.Name, (SelectList)ViewData["doDailyTasks"])

        
           
        <input type="submit" value="Run Task" />
         
        </fieldset>
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/DailyTasksComplete.cshtml
@model string


@{
    ViewBag.Title = "DailyTasksComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Daily Task Completed!</h2>

@if(string.IsNullOrWhiteSpace(ViewBag.MultilineRaw) == false)
{
    <ul>
        @foreach(var line in @ViewBag.MultilineSplitted)
        {
        <li>@line</li>
        }
    </ul>
}

<p>
    @Html.ActionLink("New Daily Task", "DailyTasks", "DriverOffence")
</p>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/Delete.cshtml
@model OOPenaltyPoints.Models.ViewModel.DriverOffenceUI

@{
    ViewBag.Title = "Delete";
}

<h2>Delete A Driver Offence</h2>

<h3>Are you sure you want to delete the driving 
offence @Html.DisplayFor(model => model.description)<br /> 
committed by @Html.DisplayFor(model => model.FName) 
@Html.DisplayFor(model => model.SName) on the 
@Html.DisplayFor(model => model.offenceDate) at 
@Html.DisplayFor(model => model.location).</h3>

@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/Details.cshtml
@model OOPenaltyPoints.Models.ViewModel.DriverOffenceUI

@{
    ViewBag.Title = "Details";
}

<h2>Details Of A Driver Offence</h2>

<fieldset>
    <legend></legend>
    <br />
    <!--------Details of driving offence committed ----------->
    <fieldset>
    <legend>Driving Offence Information:</legend>
    <br />
    <div class="display-label">Description:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.description)
    </div>

    <div class="display-label">Garda Identification No:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.gardaId)
    </div>

    <div class="display-label">Location:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.location)
    </div>

    <div class="display-label">Date:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.offenceDate)
    </div>

    <div class="display-label">Status:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.status)
    </div>
    <br />
    </fieldset>

    <!--------Details of driver who committed the offence ----------->

   <fieldset>
   <br />
   <legend>Driver Information</legend>
   <br />

    <div class="display-label">Drivers licence number (or PPSN No):</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LicenceNo)
    </div>

    <div class="display-label">Status:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LicenceStatus)
    </div>

    <div class="display-label">First Name:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FName)
    </div>

    <div class="display-label">Surname:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SName)
    </div>

    <div class="display-label">Address:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address1)
    </div>

    <div class="display-label">Town:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address2)
    </div>

    <div class="display-label">County:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address3)
    </div>
    <br />
    </fieldset>
         
    <!--------Details of vehicle used in the committed offence ----------->
   
    <fieldset>
    <legend>Vehicle Information</legend>
    <br />
    <div class="display-label">Registration No:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Registration)
    </div>

    <div class="display-label">Make:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Make)
    </div>

    <div class="display-label">Type:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>

    <div class="display-label">Capacity:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Capacity)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/SearchComplete.cshtml
@model IEnumerable<OOPenaltyPoints.Models.ViewModel.GetDriverOffenceUI>

@{
    ViewBag.Title = "SearchComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Search Results For Driver Offences Are:</h2>

<p>
    @Html.ActionLink("New Search", "Search", "DriverOffence")
</p>
<table>
    <tr>
        <th>
            Description:
        </th>
        <th>
            Date:
        </th>
        <th>
            Location:
        </th>
        <th>
            Status:
        </th>
        <th>
            Licence No:
        </th>
        <th>
            First Name:
        </th>
        <th>
            Surname:
        </th>
        <th>
            Licence Status:
        </th>
        <th>
            Vehicle Registration:
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.offenceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LicenceNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LicenceStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Registration)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/Statistics.cshtml
@model OOPenaltyPoints.Models.ViewModel.StatisticsUI

@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Driver Offence Statistics</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
 
       <fieldset>
        <legend>Select the driver offence statistics you wish to view and click the 'Generate Statistics' button when done.</legend>
           <br />

          <!--------Select the statistics list ----------->

            @Html.LabelFor(model => model.Name, "Statistics: ")
            @Html.DropDownListFor(model => model.Name, (SelectList)ViewData["doStats"])

        
           
                <input type="submit" value="Generate Statistics" />
         
        </fieldset>
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinalPenaltyPoints/PenaltyPoints/OOPenaltyPoints/Views/DriverOffence/StatisticsComplete.cshtml
@model string

@{
    ViewBag.Title = "StatisticsComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>The Driver Offence Statistics You Requested To View Are:</h2>

@if(string.IsNullOrWhiteSpace(ViewBag.MultilineRaw) == false)
{
    <ul>
        @foreach(var line in @ViewBag.MultilineSplitted)
        {
        <li>@line</li>
        }
    </ul>
}

<p>
    @Html.ActionLink("New Statistics", "Statistics", "DriverOffence")
</p>